language: java

os:
  - linux

jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
#    - '$HOME/.gradle'

#before_install:
#  - chmod +x mvnw
#  - node -v
#  - npm -v

#install:
#  - echo 'frank test'

script:
  - CI=false ./mvnw clean package -P real

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp target/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/app-quotes.zip # deploy로 zip파일 이동
  - ls before-deploy && ls deploy

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: app-quotes-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait_until_deployed: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: app-quotes-build # S3 버킷
    key: app-quotes.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: app-quotes # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: app-quotes-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      all_branches: true

#after_script:
#  - cat /home/travis/.npm/_logs/*.log

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - advenoh@gmail.com