language: java
jdk:
  - openjdk8

branches:
  only:
    - feature/quote-m1

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x mvnw

install:
  - echo 'test'

script:
  - ./mvnw -X clean package -P real

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - advenoh@gmail.com